CREATE DATABASE RoteiroLivrosManha

USE RoteiroLivrosManha

CREATE TABLE GENEROS (
IdGenero INT PRIMARY KEY IDENTITY,
Nome VARCHAR (200)
);

CREATE TABLE AUTORES (
IdAutor INT PRIMARY KEY IDENTITY,
Nome VARCHAR(200)
);

CREATE TABLE LIVROS (
IdLivros INT PRIMARY KEY IDENTITY,
Titulo VARCHAR (200),
IdGenero INT FOREIGN KEY REFERENCES GENEROS (IdGenero),
IdAutor INT FOREIGN KEY REFERENCES AUTORES (IdAutor),
);

INSERT INTO GENEROS (Nome)
VALUES	('FANTASIA EPICA'),
		('LITERARTURA DE GUERRA'),
		('FICÇÃO CIENTIFICA');

INSERT INTO AUTORES (Nome)
VALUES	('George Raymond Richard Martin'),
		('Sun Tzu'),
		('Isaac Asimov');

INSERT INTO LIVROS (Titulo, IdGenero, IdAutor)
VALUES	('I, ROBOT', 3,3 ),
		('A GUERRA DOS TRONOS', 1, 1),
		('ARTE DA GUERRA', 2, 2),
		('A FURIA DOS REIS', 1,1),
		('A DANCA DOS DRAGOES', 1, 1);

SELECT * FROM AUTORES
TRUNCATE TABLE GENEROS;

UPDATE GENEROS
SET Nome = 'EPICA'
WHERE IdGenero = 4; 

UPDATE LIVROS
SET IdGenero = 1
WHERE IdLivros = 2;

DELETE FROM LIVROS
WHERE IdLivros = 1

DELETE FROM AUTORES
WHERE IdAutor = 3


